apiVersion: assent.dev/v1alpha1
kind: MergePolicy
metadata:
  name: base
spec:
  rules:
    - name: block-policy
      phase: enforce
      match:
        files:
          paths: ["**/*.yaml"]
      effect: block
